Added UI tests for playwright
Idea-Pool/evaluation-request-interception pull request #19
Opened 2022-08-15 07:03 UTC by BenceBanyasz

2022-08-15 11:42 UTC, mgabor18 requested changes

2022-08-15 11:42 UTC, mgabor18 commented on playwright/tests/response-modification.spec.ts
> +    const text = await page.locator('[data-key=output-response]').textContent();
The selectors could be moved into a separate file, to increase code quality, and readability.

2022-08-15 11:42 UTC, mgabor18 commented on playwright/tests/response-modification.spec.ts
> +    expect(text).toEqual(modifiedBody);
I would suggest `JSON.parse`-ing the received `text`.

2022-08-15 11:42 UTC, mgabor18 commented on playwright/tests/response-validation.spec.ts
> +    expect(text).toEqual(fullBody);
I would suggest `JSON.parse`-ing the received `text`.

2022-08-30 12:20 UTC, mgabor18 approved these changes

2022-08-30 12:31 UTC, sorosz89 approved these changes

2022-08-30 13:44 UTC, merged