Feature/webdriverio request interception
Idea-Pool/evaluation-request-interception pull request #3
Opened 2022-04-06 17:31 UTC by szucst

2022-04-07 06:28 UTC, szikszail requested changes

2022-04-07 06:28 UTC, szikszail commented on webDriverIO/specs/data/list-users-schema.ts
> +const userSchema = {
I'd suggest defining these schemas using the built-in options of the JSON Schema (e.g., definitions, references, etc.).

2022-05-17 16:48 UTC, mgabor18 commented on webDriverIO/tests/request-validation.ts
> +} = require('../data/test-data.json');
Maybe you could use import here as well.
(and in the other files too.)

2022-05-17 16:48 UTC, mgabor18 commented on webDriverIO/tests/response-modification.ts
> +                const request = await browser.getRequest(0);
redeclaring `request` here is unnecessary as you use a previously declared one through your tests.

2022-05-17 16:48 UTC, mgabor18 commented on webDriverIO/tests/request-validation.ts
> +            expect(request.url).to.contain(`${ expectedURL }`);
Why do you use a template literal here for `expectedURL`?

2022-05-19 07:00 UTC, mgabor18 approved these changes

2022-05-19 08:24 UTC, merged